site_name: Ericsson Service Assurance
copyright: Copyright &copy; 2023 Ericsson AB - All Rights Reserved

use_directory_urls: false
site_dir: /site/docs

theme:
  name: material
  logo: img/ericsson_econ.svg
  favicon: img/favicon.ico
  font: false
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.sections

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/extra.js

markdown_extensions:
  - attr_list
  - md_in_html

extra:
  generator: false

plugins:
  - search
  - glightbox
  - build_plantuml:
      render: "local"
      bin_path: "/usr/bin/plantuml"
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "gen"
      input_folder: "src"
      input_extensions: "puml"

nav:
  - Home: 'index.md'

