#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eca-k6-testsuite-kafka-cert
spec:
  kubernetes:
    generatedSecretName: eca-k6-kafka-cert
    secretType: tls
  certificate:
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
    subject:
      cn:  eca-k6-testsuite
    issuer:
      reference: eric-oss-dmm-kf-op-sz-clients-ca-cert
